# Choose a build environment
dist: xenial

# # Do not choose a language; we provide our own build tools.
language: generic

sudo: false

cache:
  apt: true
  directories:
    - $HOME/.stack

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - lmodern
      - texlive-latex-base
      - texlive-latex-recommended
      - texlive-latex-extra
      - texlive-fonts-recommended
      - texlive-fonts-extra

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack --no-terminal --install-ghc test --only-dependencies

script:
 - stack --no-terminal run build
 - stack --no-terminal run check

after_success: ./bin/deploy
