language: haskell

sudo: false

cache:
    apt: true
    directories:
        - $HOME/.cabal/
        - $HOME/.ghc/

addons:
    apt:
        sources:
            - hvr-ghc
        packages:
            - cabal-install-1.22
            - ghc-7.10.1
            - texlive-full
# As neither `lmodern` nor `context` is whitelisted at time of
# writing (2015-05-30) our only choice is installing texlive-full
# to obtain them
# https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
#
# If in the future this is solved, we only need these packages:
#           - texlive-latex-base
#           - texlive-latex-recommended
#           - texlive-latex-extra
#           - texlive-fonts-recommended
#           - texlive-fonts-extra

before_install:
 - texconfig font rw
 - export PATH=$HOME/.cabal/bin:/opt/ghc/7.10.1/bin:/opt/cabal/1.22/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - cabal update
 - cabal install --avoid-reinstalls happy alex
 - cabal install --avoid-reinstalls --only-dependencies --constraint="hakyll -previewserver -watchserver -checkexternal" --disable-benchmarks --disable-coverage --disable-documentation --disable-optimization

script:
 - cabal configure
 - cabal run build
 - cabal run check

after_success: ./bin/deploy
