language: haskell

sudo: false

cache:
    apt: true
    directories:
        - $HOME/.cabal/
        - $HOME/.ghc/

addons:
    apt:
        sources:
            - hvr-ghc
        packages:
            - cabal-install-1.24
            - ghc-8.0.1
            - lmodern
            - texlive-latex-base
            - texlive-latex-recommended
            - texlive-latex-extra
            - texlive-fonts-recommended
            - texlive-fonts-extra

before_install:
 - texconfig font rw
 - export PATH=$HOME/.cabal/bin:/opt/ghc/8.0.1/bin:/opt/cabal/1.24/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - cabal update
 - cabal install --avoid-reinstalls happy alex
 - cabal install --avoid-reinstalls --only-dependencies --constraint="hakyll -previewserver -watchserver -checkexternal" --disable-benchmarks --disable-coverage --disable-documentation --disable-optimization

script:
 - cabal configure
 - cabal run build
 - cabal run check

after_success: ./bin/deploy
