language: haskell
ghc: '7.8'

# Note: the distinction between `before_install` and `install` is not important.
before_install:
 - travis_retry sudo apt-get install -y texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra
 - travis_retry sudo texconfig font rw

# only with sudo: false
# cache:
#     apt: true
#     directories:
#         - /home/travis/.cabal/

install:
 - travis_retry cabal update
 - export ORIG=`pwd`; mkdir /tmp/time; cd /tmp/time; wget https://github.com/haskell/time/archive/master.zip; unzip master.zip; cd time-master; autoreconf; cabal configure; cabal install; cd $ORIG; rm -rf /tmp/time
 - cabal install -f-previewserver -f-watchserver -f-checkexternal hakyll
 - cabal install --only-dependencies

script:
 - cabal configure
 - cabal run build
 - cabal run check
